### ISSUE TITLE
Bug: Generating a realm from a schematic crashes the game

### ISSUE THREAD

**Issue by Lowie375** [ubc-minetest-classroom/Minetest_Classroom#144] opened 2022-07-27 19:44 UTC
**Describe the bug**
Server crash occurred on an instance running from commit [`3dfa4a3`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/commit/3dfa4a3fde92d8d905d4c7f029061ac2ef463ca5) on `feature/schematicOffset` when trying to generate a realm from the `MKRF512_all` schematic using commands:
```
AsyncErr: Lua: Runtime error from mod '' in callback on_chat_message(): ...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:98: attempt to call method 'LocalToWorldPosition' (a nil value)
stack traceback:
	...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:98: in function 'Load_Schematic'
	...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:214: in function 'NewFromSchematic'
	...mes\Minetest_Classroom\mods\mc_worldmanager/commands.lua:308: in function 'func'
	...netest\minetest-5.5.1-win64\bin\..\builtin\game\chat.lua:79: in function <...netest\minetest-5.5.1-win64\bin\..\builtin\game\chat.lua:52>
	...st\minetest-5.5.1-win64\bin\..\builtin\game\register.lua:429: in function <...st\minetest-5.5.1-win64\bin\..\builtin\game\register.lua:415>
```
On rejoin, the realm appears in the realm list. When teleported to, however, it does not load.

**To Reproduce**
1. Join a MineTest world
2. Run the command `/realm schematic load MKRF512_all`
3. See server crash

**Expected behavior**
I expected a realm to be generated using the `MKRF512_all` schematic.

**Desktop:**
 - OS: Windows 10
 - MineTest Version 5.5.1

**Additional context**
- This also affects realm generation from the teacher tool
- Suspect this is an issue with just the `feature/schematicOffset` branch, since the line that causes the crash was added as part of #135. Also suspect that this is not schematic-specific, since the issue does not appear to be with the schematic files themselves

**Comment by pauldpickell** [comment] 2022-07-29 11:25
I have reproduced this crash on this branch, though in my case, I created a new world and then it crashed once I joined the world, but the spawn realm schematic was not placed. When I rejoin the world, there is still no schematic and my player is falling for a few seconds and then crashes again. This cycle repeats on rejoining and I was able to get a `/realm list` command in to see that there were multiple attempts to create the spawn realm (e.g., `Spawn : 1`, `Spawn : 2`, `Spawn : 3` etc).

**Comment by pauldpickell** [comment] 2022-07-29 16:12
I was also able to crash the UBC server with the `develop` branch. Did not start with a fresh copy, but I noticed when I toggled on `/realm coordinates hud latlong` that the coordinates were incorrect for the `MKRF512_all` map, so I created a new one with `/realm schematic load MKRF512_all` and teleported to it just fine. But when I tried `/realm setspawn`, the server crashed with a similar output from debug that Nanjou shared above:

```
ServerError: AsyncErr: Lua: Runtime error from mod '' in callback on_chat_message(): ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: attempt to call method 'WorldToLocalPosition' (a nil value)
stack traceback:
      ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: in function <...minetest_classroom/mods/mc_worldmanager/commands.lua:316>
      (tail call): ?
      /home/ubuntu/minetest/bin/../builtin/game/chat.lua:79: in function '?'
      ...ome/ubuntu/minetest/bin/../builtin/game/register.lua:429: in function <...ome/ubuntu/minetest/bin/../builtin/game/register.lua:415>
``` 

Sorry, if this is unrelated, I will open a new issue.

**Comment by lukasgolson** [comment] 2022-08-02 16:21
Interesting; I am unable to replicate this on either the pre-merge offset nor the pre-merge develop branch. This must've been introduced as a merge issue... I'll get it patched today.

**Comment by lukasgolson** [comment] 2022-08-02 16:24
I've just read through the crash log, it looks like there was a method refractor under the world coordinate HUD which obviously is missing in this branch. Submitting fix now. 

The fix is to rename coordinate conversion method calls such as `LocalToWorldPosition` to the form `LocalToWorldSpace`.

**Comment by lukasgolson** [comment] 2022-08-02 16:30
> I was also able to crash the UBC server with the `develop` branch. Did not start with a fresh copy, but I noticed when I toggled on `/realm coordinates hud latlong` that the coordinates were incorrect for the `MKRF512_all` map, so I created a new one with `/realm schematic load MKRF512_all` and teleported to it just fine. But when I tried `/realm setspawn`, the server crashed with a similar output from debug that Nanjou shared above:
> 
> ```
> ServerError: AsyncErr: Lua: Runtime error from mod '' in callback on_chat_message(): ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: attempt to call method 'WorldToLocalPosition' (a nil value)
> stack traceback:
>       ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: in function <...minetest_classroom/mods/mc_worldmanager/commands.lua:316>
>       (tail call): ?
>       /home/ubuntu/minetest/bin/../builtin/game/chat.lua:79: in function '?'
>       ...ome/ubuntu/minetest/bin/../builtin/game/register.lua:429: in function <...ome/ubuntu/minetest/bin/../builtin/game/register.lua:415>
> ```
> 
> Sorry, if this is unrelated, I will open a new issue.

This is a related bug; I forgot to carry forward the refactor.

**Comment by lukasgolson** [comment] 2022-08-02 17:54
> > I was also able to crash the UBC server with the `develop` branch. Did not start with a fresh copy, but I noticed when I toggled on `/realm coordinates hud latlong` that the coordinates were incorrect for the `MKRF512_all` map, so I created a new one with `/realm schematic load MKRF512_all` and teleported to it just fine. But when I tried `/realm setspawn`, the server crashed with a similar output from debug that Nanjou shared above:
> > ```
> > ServerError: AsyncErr: Lua: Runtime error from mod '' in callback on_chat_message(): ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: attempt to call method 'WorldToLocalPosition' (a nil value)
> > stack traceback:
> >       ...minetest_classroom/mods/mc_worldmanager/commands.lua:321: in function <...minetest_classroom/mods/mc_worldmanager/commands.lua:316>
> >       (tail call): ?
> >       /home/ubuntu/minetest/bin/../builtin/game/chat.lua:79: in function '?'
> >       ...ome/ubuntu/minetest/bin/../builtin/game/register.lua:429: in function <...ome/ubuntu/minetest/bin/../builtin/game/register.lua:415>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sorry, if this is unrelated, I will open a new issue.
> 
> This is a related bug; I forgot to carry forward the refactor.



> **Describe the bug** Server crash occurred on an instance running from commit [`3dfa4a3`](https://github.com/ubc-minetest-classroom/Minetest_Classroom/commit/3dfa4a3fde92d8d905d4c7f029061ac2ef463ca5) on `feature/schematicOffset` when trying to generate a realm from the `MKRF512_all` schematic using commands:
> 
> ```
> AsyncErr: Lua: Runtime error from mod '' in callback on_chat_message(): ...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:98: attempt to call method 'LocalToWorldPosition' (a nil value)
> stack traceback:
> 	...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:98: in function 'Load_Schematic'
> 	...om\mods\mc_worldmanager/realm/realmSchematicSaveLoad.lua:214: in function 'NewFromSchematic'
> 	...mes\Minetest_Classroom\mods\mc_worldmanager/commands.lua:308: in function 'func'
> 	...netest\minetest-5.5.1-win64\bin\..\builtin\game\chat.lua:79: in function <...netest\minetest-5.5.1-win64\bin\..\builtin\game\chat.lua:52>
> 	...st\minetest-5.5.1-win64\bin\..\builtin\game\register.lua:429: in function <...st\minetest-5.5.1-win64\bin\..\builtin\game\register.lua:415>
> ```
> 
> On rejoin, the realm appears in the realm list. When teleported to, however, it does not load.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Join a MineTest world
> 2. Run the command `/realm schematic load MKRF512_all`
> 3. See server crash
> 
> **Expected behavior** I expected a realm to be generated using the `MKRF512_all` schematic.
> 
> **Desktop:**
> 
> * OS: Windows 10
> * MineTest Version 5.5.1
> 
> **Additional context**
> 
> * This also affects realm generation from the teacher tool
> * Suspect this is an issue with just the `feature/schematicOffset` branch, since the line that causes the crash was added as part of [Feature/schematic offset #135](https://github.com/ubc-minetest-classroom/Minetest_Classroom/pull/135). Also suspect that this is not schematic-specific, since the issue does not appear to be with the schematic files themselves

Both issues are now fixed on the realmOffset branch.

**Closed as completed by lukasgolson** 2022-08-02 17:54 UTC
Labels: bug
