### ISSUE TITLE
Task timer stops when instructor presses "esc" 

### ISSUE THREAD

**Issue by mandyhuy** [ubc-minetest-classroom/Minetest_Classroom#118] opened 2022-07-06 08:52 UTC
**Describe the bug**
The task timer stops when game is paused (i.e., "esc" on the keyboard is pressed). It happens with a player that has instructor privileges (don't know if it also happens with a student player). 

**To Reproduce**
1. Activate teacher privilege
2. Submit an example task, with a timer 
3. Press "esc" 
4. See timer displayed at the bottom of the screen stop

**Expected behavior**
The task timer should still continue even when "esc" is pressed, both from the instructor and student perspectives. 

**Additional context**

**Comment by Lowie375** [comment] 2022-07-15 23:06
@mandyhuy I have a few questions about the bug:

- Did this happen on singleplayer or on a server?
- Were you the only player in your MineTest world when this happened?

**Comment by mandyhuy** [comment] 2022-07-16 14:48
@Lowie375: 

- I believe singleplayer, because it says "Game info: - Mode: Singleplayer" on the "Game paused" formspec. 
- I can't be sure, but there's a high chance that I was. I'm not sure how to check if there are other players in the world.

**Comment by pauldpickell** [comment] 2022-07-23 18:11
I cannot reproduce this in singleplayer mode as the teacher who initiates the task on Windows and Minetest 5.5.1 nor could I reproduce when joined with only one player on the server. @mandyhuy are you using MacOS? When did you press `esc`? When the task formspec is shown to the player? After pressing "OK" on the task formspec?

**Comment by Lowie375** [comment] 2022-07-23 18:19
I was able to reproduce this on a singleplayer world on Windows/MineTest 5.5.1
I suspect this may have something to do with the game itself, since the timer is run using a sequence of `minetest.after` calls: pausing the game may pause any in-world timing on singleplayer. If this is the case, this may not be able to be fixed on singleplayer.

**Comment by lukasgolson** [comment] 2022-07-23 20:03
Reproduced in true single player (when the server mode was disabled).

**Closed as not planned** 2023-06-15 01:36 UTC
Labels: bug, question
