### ISSUE TITLE
Server crashes when creating a new classroom

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#2] opened 2022-05-09 20:54 UTC
When creating a new classroom with the Vancouver DEM-based world, the server crashed after 45 seconds.

Need to reproduce this error.

**Comment by pauldpickell** [comment] 2022-05-09 22:14
Not yet reproduced on the server, but this seems to be solved for the single player mode with #5. 
Edit: Can confirm that #5 fixes the server crash as well. Closing this issue now.

**Closed as completed** 2022-05-09 22:35 UTC
Labels: bug
